//! Generate a starter R analysis script to accompany the exported tidy
//! per-population CSV. Pure string generation (unit-tested).
//!
//! Philosophy: the value for an R-fluent user is the **plumbing** (read + the
//! channel-collapse reshape) and the **flow-stats caveats**, not the test choice
//! (which they'll swap). So: base R only — no `library()` that errors on a missing
//! package — descriptives + an exploratory plot + ONE clearly-labeled worked example,
//! never an auto p-value table across populations (underpowered + uncorrected at
//! typical flow n, and it reads as naive).

/// Build the `.R` text. `csv_basename` is the file the script reads (written next to
/// it); `groups` are the distinct, non-empty condition tags; `populations` the gate
/// names (to seed a worked example).
pub fn r_script(csv_basename: &str, groups: &[String], populations: &[String], version: &str) -> String {
    let csv = csv_basename; // local binding so `{csv:?}` below isn't the `csv` crate
    let levels = if groups.is_empty() {
        String::new()
    } else {
        let quoted: Vec<String> = groups.iter().map(|g| format!("{:?}", g)).collect();
        format!(", levels = c({})", quoted.join(", "))
    };

    // Pick a worked-example population: prefer a real gate over the "All events" root.
    let example_pop = populations.iter()
        .find(|p| !p.eq_ignore_ascii_case("All events"))
        .or_else(|| populations.first())
        .cloned()
        .unwrap_or_else(|| "All events".to_string());

    // Group-count-aware worked example (the user edits this).
    let worked = match groups.len() {
        0 | 1 => "\
# No condition groups are tagged yet — tag them in the Samples list and re-export,
# then a group comparison goes here. The descriptives and plot above already work."
            .to_string(),
        2 => "\
# Two groups -> Wilcoxon (robust) is a reasonable default; swap for t.test or
# lm(pct_parent ~ group, data = ex) as your design warrants.
print(wilcox.test(pct_parent ~ group, data = ex))"
            .to_string(),
        n => format!("\
# {n} groups -> Kruskal-Wallis (non-parametric) or a linear model. Pick one:
print(kruskal.test(pct_parent ~ group, data = ex))
# print(summary(aov(pct_parent ~ group, data = ex)))"),
    };

    format!(r#"# ============================================================================
# flowcyto R bridge -- starting scaffold (generated by flowcyto v{version}).
# A DRAFT to edit, not a finished analysis. Runs in base R (no packages needed).
# Reads the tidy per-population table exported alongside this file.
# ============================================================================

d <- read.csv({csv:?}, stringsAsFactors = FALSE)

# Condition / group factor (set the order you want for plots and contrasts):
d$group <- factor(d$group{levels})
cat("Tubes per group:\n"); print(table(unique(d[, c("group", "sample")])$group))

# -- Population frequencies --------------------------------------------------
# count / pct_parent / pct_total are per-POPULATION: identical across the channel
# rows of a given sample, so collapsing on the non-channel columns is exact. (This
# is the tedious reshape this file automates; it relies on popstats emitting one
# count per population, which it does.)
freq <- unique(d[, c("group", "sample", "population", "parent", "depth",
                     "count", "pct_parent", "pct_total")])

# Descriptives: n, mean, SD of %parent by population x group.
summ <- aggregate(pct_parent ~ population + group, data = freq,
                  FUN = function(x) c(n = length(x), mean = mean(x), sd = sd(x)))
print(summ)

# -- Exploratory plot (base R; a ggplot2 version is at the bottom) -----------
pops <- unique(freq$population)
op <- par(no.readonly = TRUE)
par(mfrow = c(ceiling(length(pops) / 3), 3), mar = c(3, 4, 2, 1))
for (p in pops) {{
  stripchart(pct_parent ~ group, data = freq[freq$population == p, ],
             vertical = TRUE, method = "jitter", pch = 19,
             main = p, ylab = "% of parent")
}}
par(op)

# -- Starter statistical test -- PICK YOUR OWN MODEL -------------------------
# Flow-cytometry statistics, please read:
#   * The unit of replication is the TUBE / animal -- each sample is ONE observation.
#     Do NOT fit cell-count GLMMs that treat individual cells as replicates: that
#     pseudoreplicates and produces spuriously tiny p-values.
#   * If samples are nested in experiments / batches, add that as a block or random
#     effect, e.g. lme4::lmer(pct_parent ~ group + (1 | experiment)).
#   * Rare populations (%parent near 0) misbehave on the raw scale -- consider a
#     logit / arcsine transform or a proportion-appropriate GLM.
#   * Testing many populations -> correct for multiple comparisons (see p.adjust()).
#
# One worked example on a single population (edit the population and the model):
ex <- freq[freq$population == {example_pop:?}, ]
{worked}

# -- MFI (median fluorescence) per population x channel ----------------------
# mfi <- d[d$channel == "FITC-A", c("group", "sample", "population", "median")]
# print(aggregate(median ~ population + group, data = mfi, FUN = mean))

# -- ggplot2 alternative (needs: install.packages("ggplot2")) ----------------
# library(ggplot2)
# ggplot(freq, aes(group, pct_parent)) +
#   geom_boxplot(outlier.shape = NA) + geom_jitter(width = .15, alpha = .6) +
#   facet_wrap(~ population, scales = "free_y") + theme_bw()
"#)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn two_groups_uses_wilcoxon_and_levels() {
        let r = r_script("my_data.csv", &["ctrl".into(), "treated".into()],
                         &["All events".into(), "Live".into(), "CD3+".into()], "9.9.9");
        assert!(r.contains(r#"read.csv("my_data.csv""#), "reads the named CSV");
        assert!(r.contains(r#"levels = c("ctrl", "treated")"#), "sets the group levels");
        assert!(r.contains("wilcox.test"), "two groups -> Wilcoxon example");
        assert!(!r.contains("kruskal.test"));
        // worked example seeds on a real gate, not the root:
        assert!(r.contains(r#"population == "Live""#) || r.contains(r#"population == "CD3+""#));
        // the load-bearing caveats are present verbatim-ish:
        assert!(r.contains("pseudoreplicates"));
        assert!(r.contains("unit of replication is the TUBE"));
        // base R only — no hard library() at the top that would error on line 1.
        assert!(!r.lines().any(|l| l.trim_start().starts_with("library(")));
    }

    #[test]
    fn three_groups_uses_kruskal() {
        let r = r_script("d.csv", &["a".into(), "b".into(), "c".into()], &["P".into()], "0");
        assert!(r.contains("kruskal.test"));
        assert!(!r.contains("wilcox.test"));
        assert!(r.contains("3 groups"));
    }

    #[test]
    fn no_groups_degrades_gracefully() {
        let r = r_script("d.csv", &[], &["All events".into()], "0");
        assert!(r.contains("No condition groups are tagged"));
        assert!(r.contains("d$group <- factor(d$group)"), "no levels when no groups");
        assert!(!r.contains("wilcox.test") && !r.contains("kruskal.test"));
    }
}
