//! Self-contained HTML reproducibility report — full provenance of one analysis in a
//! single file (inline CSS, no external assets): the sample + instrument, compensation
//! matrix and its source, display transforms, the gating strategy, per-population
//! statistics, the flowCore-validation note, and the gate JSON for machine re-import.
//! Pure generation (`html`); the GUI gathers `ReportData` from its state.

use crate::popstats::PopulationStatsTable;

pub struct ChannelRow {
    pub name: String,
    pub stain: String,
    pub transform: String,
}

pub struct GateRow {
    pub depth: usize,
    pub name: String,
    pub parent: String,
    pub channels: String,
    pub shape: String,
}

pub struct ReportData {
    pub version: String,
    pub generated: String,
    pub file_name: String,
    pub n_events: usize,
    pub cytometer: String,
    pub acq_date: String,
    pub channels: Vec<ChannelRow>,
    pub compensated: bool,
    pub spill_channels: Vec<String>, // empty ⇒ no compensation matrix
    pub spill_rows: Vec<Vec<f64>>,
    pub spill_source: String,
    pub gates: Vec<GateRow>,
    pub stats: Option<PopulationStatsTable>,
    pub gates_json: String,
}

/// Escape text for safe HTML embedding (data-derived strings: names, stains, gates…).
fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
}

/// Current UTC time as "YYYY-MM-DD HH:MM:SS UTC" (dependency-free; civil-from-days).
pub fn now_utc() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as i64;
    civil(secs)
}

fn civil(secs: i64) -> String {
    let days = secs.div_euclid(86400);
    let tod = secs.rem_euclid(86400);
    let (h, mi, s) = (tod / 3600, (tod % 3600) / 60, tod % 60);
    // Howard Hinnant's civil_from_days.
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{:04}-{:02}-{:02} {:02}:{:02}:{:02} UTC", y, m, d, h, mi, s)
}

fn fmt_num(v: f64) -> String {
    if v.is_finite() { format!("{:.2}", v) } else { "—".to_string() }
}

/// Build the complete, self-contained HTML document.
pub fn html(r: &ReportData) -> String {
    let mut h = String::new();
    h.push_str(&format!(
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>flowcyto report — {}</title>\n<style>{}</style>\n</head><body>\n\
         <div class=\"wrap\">\n",
        esc(&r.file_name), CSS
    ));
    h.push_str(&format!(
        "<h1>flowcyto analysis report</h1>\n\
         <p class=\"meta\">Generated by flowcyto v{} · {}</p>\n",
        esc(&r.version), esc(&r.generated)
    ));

    // Sample.
    h.push_str("<h2>Sample</h2>\n<table class=\"kv\">\n");
    for (k, v) in [
        ("File", r.file_name.clone()),
        ("Events", r.n_events.to_string()),
        ("Cytometer", r.cytometer.clone()),
        ("Acquired", r.acq_date.clone()),
    ] {
        h.push_str(&format!("<tr><th>{}</th><td>{}</td></tr>\n", k, esc(&v)));
    }
    h.push_str("</table>\n");

    // Channels & transforms.
    h.push_str("<h2>Channels &amp; display transforms</h2>\n\
                <table><thead><tr><th>Channel</th><th>Stain</th><th>Transform</th></tr></thead><tbody>\n");
    for c in &r.channels {
        h.push_str(&format!("<tr><td>{}</td><td>{}</td><td>{}</td></tr>\n",
            esc(&c.name), esc(&c.stain), esc(&c.transform)));
    }
    h.push_str("</tbody></table>\n");

    // Compensation.
    h.push_str("<h2>Compensation</h2>\n");
    if !r.compensated {
        h.push_str("<p class=\"note\">Not applied — analysis is on raw (uncompensated) data.</p>\n");
    } else if r.spill_channels.is_empty() {
        h.push_str("<p class=\"note\">Compensation enabled, but no spillover matrix was present.</p>\n");
    } else {
        h.push_str(&format!("<p class=\"note\">Source: {}</p>\n", esc(&r.spill_source)));
        h.push_str("<table class=\"matrix\"><thead><tr><th>spill →</th>");
        for c in &r.spill_channels {
            h.push_str(&format!("<th>{}</th>", esc(c)));
        }
        h.push_str("</tr></thead><tbody>\n");
        for (i, row) in r.spill_rows.iter().enumerate() {
            h.push_str(&format!("<tr><th>{}</th>", esc(r.spill_channels.get(i).map(|s| s.as_str()).unwrap_or(""))));
            for (j, v) in row.iter().enumerate() {
                let cls = if i == j { " class=\"diag\"" } else if v.abs() > 1e-9 { " class=\"off\"" } else { "" };
                h.push_str(&format!("<td{}>{:.4}</td>", cls, v));
            }
            h.push_str("</tr>\n");
        }
        h.push_str("</tbody></table>\n");
    }

    // Gating strategy.
    h.push_str("<h2>Gating strategy</h2>\n");
    if r.gates.is_empty() {
        h.push_str("<p class=\"note\">No gates defined.</p>\n");
    } else {
        h.push_str("<table><thead><tr><th>Population</th><th>Parent</th><th>Channels</th><th>Definition</th></tr></thead><tbody>\n");
        for g in &r.gates {
            let indent = "&nbsp;&nbsp;".repeat(g.depth);
            h.push_str(&format!(
                "<tr><td>{}{}</td><td>{}</td><td>{}</td><td class=\"mono\">{}</td></tr>\n",
                indent, esc(&g.name), esc(&g.parent), esc(&g.channels), esc(&g.shape)
            ));
        }
        h.push_str("</tbody></table>\n");
    }

    // Population statistics.
    h.push_str("<h2>Population statistics</h2>\n");
    if let Some(t) = &r.stats {
        h.push_str("<div class=\"scroll\"><table><thead><tr>\
                    <th>Population</th><th>Count</th><th>%Parent</th><th>%Total</th>");
        for ch in &t.channels {
            h.push_str(&format!("<th>{}<br><span class=\"sub\">MFI</span></th>", esc(ch)));
        }
        h.push_str("</tr></thead><tbody>\n");
        for row in &t.rows {
            let indent = "&nbsp;&nbsp;".repeat(row.depth);
            h.push_str(&format!(
                "<tr><td>{}{}</td><td>{}</td><td>{}</td><td>{}</td>",
                indent, esc(&row.name), row.count, fmt_num(row.pct_parent), fmt_num(row.pct_total)
            ));
            for m in &row.medians {
                h.push_str(&format!("<td>{}</td>", fmt_num(*m)));
            }
            h.push_str("</tr>\n");
        }
        h.push_str("</tbody></table></div>\n");
    } else {
        h.push_str("<p class=\"note\">No statistics computed.</p>\n");
    }

    // Reproducibility.
    h.push_str("<h2>Reproducibility</h2>\n\
        <p>The numeric layers (parsing, compensation, asinh, logicle) are validated \
        against R/flowCore — run <code>flowcyto selftest</code> to reproduce the benchmark. \
        The gating below can be re-imported into flowcyto (Gates → Load).</p>\n");
    h.push_str(&format!(
        "<details><summary>Gate definitions (JSON)</summary><pre class=\"json\">{}</pre></details>\n",
        esc(&r.gates_json)
    ));

    h.push_str("</div>\n</body></html>\n");
    h
}

const CSS: &str = "\
*{box-sizing:border-box} body{margin:0;background:#f4f6f9;color:#1d2127;\
font:14px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif}\
.wrap{max-width:980px;margin:32px auto;padding:0 24px}\
h1{font-size:24px;margin:0 0 4px} h2{font-size:17px;margin:28px 0 10px;color:#1d2127;\
border-bottom:2px solid #26a29c;padding-bottom:4px;display:inline-block}\
.meta{color:#6b7280;margin:0 0 8px} .note{color:#6b7280}\
table{border-collapse:collapse;width:100%;background:#fff;border:1px solid #e3e7ec;\
border-radius:8px;overflow:hidden;margin:4px 0 8px}\
th,td{padding:6px 10px;text-align:left;border-bottom:1px solid #eef1f4;font-variant-numeric:tabular-nums}\
thead th{background:#eef3f3;color:#243; font-weight:600} tr:last-child td{border-bottom:none}\
table.kv th{width:140px;color:#6b7280} table.kv,table.matrix{width:auto}\
.matrix td{text-align:right} .matrix td.diag{background:#eef3f3;color:#9aa} \
.matrix td.off{background:#fff3ec;color:#b4521e} .matrix th{background:#eef3f3}\
.mono,.json{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}\
.mono{font-size:12px;color:#374151} .sub{font-weight:400;color:#9aa;font-size:11px}\
.scroll{overflow-x:auto} td{font-size:13px}\
details{margin-top:8px} summary{cursor:pointer;color:#26a29c}\
pre.json{background:#1e2128;color:#dfe3ea;padding:12px;border-radius:8px;overflow:auto;font-size:12px;white-space:pre-wrap}\
code{background:#eef1f4;padding:1px 5px;border-radius:4px;font-family:ui-monospace,Menlo,monospace}";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn civil_from_known_epoch() {
        // 1700000000 = 2023-11-14 22:13:20 UTC.
        assert_eq!(civil(1_700_000_000), "2023-11-14 22:13:20 UTC");
        assert_eq!(civil(0), "1970-01-01 00:00:00 UTC");
    }

    #[test]
    fn html_has_sections_and_escapes() {
        let r = ReportData {
            version: "9.9.9".into(), generated: "2026-01-01 00:00:00 UTC".into(),
            file_name: "a<b>.fcs".into(), n_events: 1234, cytometer: "LSRII".into(),
            acq_date: "01-JAN-2026".into(),
            channels: vec![ChannelRow { name: "FITC-A".into(), stain: "CD3".into(), transform: "Logicle".into() }],
            compensated: true,
            spill_channels: vec!["FITC-A".into(), "PE-A".into()],
            spill_rows: vec![vec![1.0, 0.08], vec![0.03, 1.0]],
            spill_source: "embedded $SPILLOVER".into(),
            gates: vec![GateRow { depth: 1, name: "CD3+".into(), parent: "Live".into(),
                                  channels: "FITC-A (Logicle)".into(), shape: "interval [1.2, 4.5]".into() }],
            stats: None, gates_json: "[{\"id\":1}]".into(),
        };
        let h = html(&r);
        assert!(h.contains("flowcyto analysis report"));
        assert!(h.contains("Compensation") && h.contains("Gating strategy") && h.contains("flowcyto selftest"));
        assert!(h.contains("a&lt;b&gt;.fcs"), "file name must be HTML-escaped");
        assert!(!h.contains("a<b>.fcs"), "raw unescaped name must not appear");
        assert!(h.contains("CD3+") && h.contains("1234"));
    }
}
